permissions:
  contents: read
name: rex integration tests
on:
  push:
    branches: ["main"]
  merge_group:
  pull_request:
    branches: ["**"]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  sdk-integration-test:
    name: Integration Test - SDK
    runs-on: ubuntu-latest

    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          large-packages: false
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Rust Environment
        uses: ./.github/actions/setup-rust

      - name: Install solc
        uses: pontem-network/get-solc@master
        with:
          version: v0.8.29
          token: ${{ secrets.GITHUB_TOKEN || '' }}

      - name: Install ethrex
        run: |
          cd ..
          git clone https://github.com/lambdaclass/ethrex.git
          echo "ethrex installed successfully"

      # also creates empty verification keys (as workflow runs with exec backend)
      - name: Build prover
        run: |
          cd ../ethrex/crates/l2
          make build-prover
          mkdir -p prover/zkvm/interface/sp1/out && touch prover/zkvm/interface/sp1/out/riscv32im-succinct-zkvm-vk

      - name: Build L1 docker image
        uses: docker/build-push-action@v6
        with:
          context: ../ethrex/
          file: ../ethrex/crates/blockchain/dev/Dockerfile
          tags: ethrex_dev:latest
          push: false

      - name: Start L1 & Deploy contracts
        run: |
          cd  ../ethrex/crates/l2
          touch .env
          CI_ETHREX_WORKDIR=/usr/local/bin \
          ETHREX_DEPLOYER_DEPLOY_RICH=true \
          ETHREX_DEPLOYER_PICO_CONTRACT_ADDRESS=0x00000000000000000000000000000000000000aa \
          ETHREX_DEPLOYER_SP1_CONTRACT_ADDRESS=0x00000000000000000000000000000000000000aa \
          ETHREX_DEPLOYER_RISC0_CONTRACT_ADDRESS=0x00000000000000000000000000000000000000aa \
          ETHREX_L2_VALIDIUM=false \
          docker compose -f docker-compose-l2.yaml up contract_deployer

      - name: Start Sequencer
        run: |
          cd  ../ethrex/crates/l2
          CI_ETHREX_WORKDIR=/usr/local/bin \
          ETHREX_L2_VALIDIUM=false \
          ETHREX_WATCHER_BLOCK_DELAY=0 \
          docker compose -f docker-compose-l2.yaml up --detach ethrex_l2

      - name: Run test
        run: |
          sudo chmod -R a+rw ../ethrex/crates/l2
          cd ../ethrex/crates/l2
          RUST_LOG=info,ethrex_prover_lib=debug make init-prover &
          docker logs --follow ethrex_l2 &
          cd /home/runner/work/rex/rex/sdk
          PROPOSER_COINBASE_ADDRESS=0x0007a881CD95B1484fca47615B64803dad620C8d cargo test --package rex-sdk --test tests -- --nocapture --test-threads=1
          killall ethrex_prover -s SIGINT

# The purpose of this job is to add it as a required check in GitHub so that we don't have to add every individual job as a required check
  all-tests:
    #Â "Integration Test" is a required check, don't change the name
    name: Integration Test
    runs-on: ubuntu-latest
    needs: [sdk-integration-test]
    # Make sure this job runs even if the previous jobs failed or were skipped
    if: ${{ always() && needs.sdk-integration-test.result != 'skipped' }}
    steps:
      - name: Check if any job failed
        run: |
          if [ "${{ needs.sdk-integration-test.result }}" != "success" ]; then
            echo "Job SDK integration test Check failed"
            exit 1
          fi
